services:
  anvil:
    build:
      dockerfile: Dockerfile.anvil
    volumes:
      - ./data/anvil:/state
    environment:
      ANVIL_STATE: "/state/anvil"
      ANVIL_STATE_INTERVAL: 10
      ANVIL_CHAIN_ID: 7566690 # sub -> hex -> decimal
      ANVIL_AUTO_IMPERSONATE: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpc.entrypoints=websecure"
      - "traefik.http.routers.rpc.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.rpc.middlewares=auth"
      - "traefik.http.services.rpc.loadbalancer.server.port=8545"
      
  faucet:
    build:
      dockerfile: Dockerfile.faucet
    depends_on:
      - anvil
    environment:
      PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faucet.entrypoints=websecure"
      - "traefik.http.routers.faucet.rule=Host(`faucet.${DOMAIN}`)"
      - "traefik.http.routers.faucet.middlewares=auth"
      - "traefik.http.services.faucet.loadbalancer.server.port=80"

  otterscan:
    image: otterscan/otterscan:v2.6.1
    volumes:
      - ./config/otterscan/config.json:/usr/share/nginx/html/config.json
    environment:
      DISABLE_CONFIG_OVERWRITE: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.entrypoints=websecure"
      - "traefik.http.routers.explorer.rule=Host(`explorer.${DOMAIN}`)"
      - "traefik.http.routers.explorer.middlewares=auth"
      - "traefik.http.services.explorer.loadbalancer.server.port=80"

  sourcify:
    image: ghcr.io/ethereum/sourcify/server:staging
    volumes:
      - ./data/sourcify:/data
      - ./config/sourcify/chains.json:/home/app/services/server/dist/sourcify-chains.json
      - ./config/sourcify/local.js:/home/app/services/server/dist/config/local.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sourcify.entrypoints=websecure"
      - "traefik.http.routers.sourcify.rule=Host(`sourcify.${DOMAIN}`)"
      #- "traefik.http.routers.sourcify.middlewares=auth"
      - "traefik.http.services.sourcify.loadbalancer.server.port=5555"

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'scroll:http://anvil:8545'
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - '5001:5001'
    volumes:
      - ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres:/var/lib/postgresql/data

  traefik:
    image: "traefik:v3.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/usersFile:/etc/traefik/usersFile"
      - "./data/traefik/acme:/acme"
    command:
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.email=mpalhas@gmail.com"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/usersFile"
