FROM oven/bun:latest
WORKDIR /app
COPY faucet/package.json faucet/bun.lockb /app
RUN bun install
COPY faucet /app
RUN bun next build
COPY entrypoint.faucet.sh /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
