#!/usr/bin/env bash

set -ue

function do_file() {
  INPUT=$1.template
  OUTPUT=$1

  cat $INPUT |\
    sed "s/{{DOMAIN}}/$DOMAIN/g" |\
    sed "s/{{BASIC_AUTH}}/$BASIC_AUTH/g" |\
    sed "s/{{CHAIN_ID}}/${CHAIN_ID}/" |\
    sed "s/{{ETH_NAME}}/${ETH_NAME}/" |\
    sed "s/{{ETH_SYMBOL}}/${ETH_SYMBOL}/" |\
    sed "s/{{CHAIN_NAME}}/${CHAIN_NAME}/" > $OUTPUT
  echo "generating ${OUTPUT}"
}

do_file "config/otterscan/config.json"
do_file "config/sourcify/chains.json"
