#!/usr/bin/env bash

set -ue

function do_file() {
  INPUT=$1.template
  OUTPUT=$1

  cat $INPUT | sed "s/{{DOMAIN}}/$DOMAIN/g" | sed "s/{{CHAIN_ID}}/${CHAIN_ID}/" > $OUTPUT
  echo "generating ${OUTPUT}"
}

do_file "config/otterscan/config.json"
do_file "config/sourcify/chains.json"
